import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import AnimatedSection from '../../components/AnimatedSection';

export const metadata = {
  title: 'Terms of Service — ShikshaSetu',
  description: 'Read the terms of service for using the ShikshaSetu learning management platform.',
};

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: `By creating an account or using ShikshaSetu, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform. We reserve the right to update these terms at any time, and continued use constitutes acceptance of any changes.`,
  },
  {
    title: '2. Account Responsibilities',
    content: `You are responsible for maintaining the security of your account credentials. You must provide accurate information during registration. You may not share your account or use another person's account without permission. You must be at least 13 years old to create an account.`,
  },
  {
    title: '3. Acceptable Use',
    content: `You agree to use ShikshaSetu only for lawful educational purposes. You may not: upload harmful or inappropriate content, attempt to breach platform security, use AI tools to generate misleading academic submissions, harass other users, or interfere with the platform's operation.`,
  },
  {
    title: '4. Content & Intellectual Property',
    content: `Course content created by teachers remains their intellectual property. Notes, quizzes, and summaries generated by AI tools are provided for personal educational use. The ShikshaSetu platform, its design, code, and branding are protected by copyright and may not be reproduced without permission.`,
  },
  {
    title: '5. AI-Generated Content',
    content: `AI-powered features (Tutor, Quiz Generator, Summarizer, Planner) provide suggestions and content that may not always be accurate. Users should verify AI-generated information and not rely on it as the sole source of academic truth. ShikshaSetu is not responsible for errors in AI-generated content.`,
  },
  {
    title: '6. Teacher & Admin Roles',
    content: `Teachers are responsible for the accuracy of course content they publish. Admins have elevated platform privileges and must use them responsibly. ShikshaSetu reserves the right to revoke elevated roles in case of misuse.`,
  },
  {
    title: '7. Certificates',
    content: `Certificates earned on ShikshaSetu indicate completion of course material on our platform. They do not constitute official academic credentials unless explicitly stated by the course provider. Certificate verification is available via unique certificate numbers.`,
  },
  {
    title: '8. Service Availability',
    content: `We strive to keep ShikshaSetu available 24/7, but we do not guarantee uninterrupted service. Scheduled maintenance, updates, and unforeseen issues may cause temporary downtime. We will notify users of planned maintenance when possible.`,
  },
  {
    title: '9. Termination',
    content: `You may delete your account at any time through your settings. We reserve the right to suspend or terminate accounts that violate these terms. Upon termination, your data will be handled in accordance with our Privacy Policy.`,
  },
  {
    title: '10. Limitation of Liability',
    content: `ShikshaSetu is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from use of the platform. Our total liability shall not exceed the amount paid by you, if any, for premium services.`,
  },
];

export default function TermsPage() {
  return (
    <main className="bg-slate-950 text-slate-100">
      <Navbar />

      {/* Hero */}
      <AnimatedSection className="relative overflow-hidden px-6 py-20 sm:px-10 lg:px-16">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_20%,rgba(139,92,246,0.08),transparent_50%)]" />
        <div className="relative mx-auto max-w-4xl text-center">
          <p className="text-sm font-semibold uppercase tracking-[0.3em] text-violet-400/80">Legal</p>
          <h1 className="mt-4 text-4xl font-bold text-white sm:text-5xl">Terms of Service</h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-300">
            Please read these terms carefully before using ShikshaSetu. They govern your use of our platform and services.
          </p>
          <p className="mt-4 text-sm text-slate-500">Last updated: July 2026</p>
        </div>
      </AnimatedSection>

      {/* Content */}
      <AnimatedSection className="border-t border-slate-800/70 px-6 py-16 sm:px-10 lg:px-16">
        <div className="mx-auto max-w-3xl space-y-10">
          {sections.map((section) => (
            <div key={section.title} className="space-y-3">
              <h2 className="text-xl font-semibold text-white">{section.title}</h2>
              <p className="text-base leading-7 text-slate-400">{section.content}</p>
            </div>
          ))}

          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 mt-12">
            <p className="text-sm text-slate-400">
              Questions about these terms? Contact us at{' '}
              <a href="mailto:support@shikshasetu.com" className="font-semibold text-violet-400 hover:text-violet-300 transition">
                support@shikshasetu.com
              </a>
            </p>
          </div>
        </div>
      </AnimatedSection>

      <Footer />
    </main>
  );
}
